<?php
echo'
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>X-SERVER | Semua Ada Untukmu</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head> 
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">X-SERVER</a>
        </div>
        <!-- Collection of nav links and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="#">Youtube</a></li>
                <li><a href="http://fdci-indonesia.web.id">Blog</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="http://fb.me/basmal109">Contact Me</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="alert alert-warning">
  <strong>Info!</strong> Isi semua kotak agar hasilnya terlihat bagus
</div>
 <div class="panel-group">
    <div class="panel panel-info">
      <div class="panel-heading">Deface Page Creator</div>
      <div class="panel-body">

<form action="" method="post">
Nick Kamu: 
<input type="text" name="nick" class="form-control" placeholder="Nick Kamu"><br/>
Judul/Title Script: <input type="text" class="form-control" name="title" placeholder="Hacked By "><br/>
Deskripsi: <input type="text" class="form-control" name="deskripsi" placeholder="This Website Has Been Hacked"><br/>
Link Gambar : <input type="text" class="form-control" name="gambar" placeholder="http://link.com/logo.jpg"><br/>
Nick Teman-teman Kamu: <input type="text" class="form-control" name="nt" placeholder="Teman1 - Teman2"><br/>
Nama Scriptnya: <input type="text" class="form-control" name="file" placeholder="depesku"><br/>
Pesan Kamu:<textarea class="form-control" name="pesan"></textarea><br/>
<input class="btn btn-info btn-md" type="submit" name="submit" value="Buat Script Defacenya"></form></div>
    </div>
';
if(isset($_POST['submit'])){
	$pesan=$_POST['pesan'];
	$nick=$_POST['nick'];
	$nickteman=$_POST['nt'];
	$bg=$_POST['bg'];
	$title=$_POST['title'];
	$deskripsi=$_POST['deskripsi'];
	$gambar=$_POST['gambar'];
	$file=$_POST['file'];
	$isiin=fopen("$file.html", "w");
	fwrite($isiin, '<!-- Generated By KannaiX007 -->
<html><head>
<title>'.$title.'</title>
<meta name="author" content="'.nick.'"/>
	<meta name="description" content="'.$deskripsi.'"/>
	<meta property="og:image" content="'.$gambar.'"/>
	<link rel="shortcut icon" href="'.$gambar.'"/>
</head>
<style>
	font{font-size:20px; color:white;}
	red{color:red;}
	.error { text-align: center; -webkit-animation: noise-3 1s linear infinite; animation: noise-3 1s linear infinite; overflow: default; }
 .info { text-align: center; width: 200px; height: 60px; margin: auto; position: absolute; top: 280px; bottom: 0; left: 20px; right: 0; -webkit-animation: noise-3 1s linear infinite; animation: noise-3 1s linear infinite; }
 .info:after { font-family: OCR-A; font-size: 100px; text-align: center; width: 800px; margin: auto; position: absolute; top: 20px; bottom: 0; left: 40px; right: 0; opacity: 0; color: white; -webkit-animation: noise-1 .2s linear infinite; animation: noise-1 .2s linear infinite; } @-webkit-keyframes noise-1 { 0%, 20%, 40%, 60%, 70%, 90% {opacity: 0;} 10% {opacity: .1;} 50% {opacity: .5; left: -6px;} 80% {opacity: .3;} 100% {opacity: .6; left: 2px;} } @keyframes noise-1 { 0%, 20%, 40%, 60%, 70%, 90% {opacity: 0;} 10% {opacity: .1;} 50% {opacity: .5; left: -6px;} 80% {opacity: .3;} 100% {opacity: .6; left: 2px;} } @-webkit-keyframes noise-2 { 0%, 20%, 40%, 60%, 70%, 90% {opacity: 0;} 10% {opacity: .1;} 50% {opacity: .5; left: 6px;} 80% {opacity: .3;} 100% {opacity: .6; left: -2px;} } @keyframes noise-2 { 0%, 20%, 40%, 60%, 70%, 90% {opacity: 0;} 10% {opacity: .1;} 50% {opacity: .5; left: 6px;} 80% {opacity: .3;} 100% {opacity: .6; left: -2px;} } @-webkit-keyframes noise { 0%, 3%, 5%, 42%, 44%, 100% {opacity: 1; -webkit-transform: scaleY(1); transform: scaleY(1);} 4.3% {opacity: 1; -webkit-transform: scaleY(1.7); transform: scaleY(1.7);} 43% {opacity: 1; -webkit-transform: scaleX(1.5); transform: scaleX(1.5);} } @keyframes noise { 0%, 3%, 5%, 42%, 44%, 100% {opacity: 1; -webkit-transform: scaleY(1); transform: scaleY(1);} 4.3% {opacity: 1; -webkit-transform: scaleY(1.7); transform: scaleY(1.7);} 43% {opacity: 1; -webkit-transform: scaleX(1.5); transform: scaleX(1.5);} } @-webkit-keyframes noise-3 { 0%,3%,5%,42%,44%,100% {opacity: 1; -webkit-transform: scaleY(1); transform: scaleY(1);} 4.3% {opacity: 1; -webkit-transform: scaleY(4); transform: scaleY(4);} 43% {opacity: 1; -webkit-transform: scaleX(10) rotate(60deg); transform: scaleX(10) rotate (60deg);} } @keyframes noise-3 { 0%,3%,5%,42%,44%,100% {opacity: 1; -webkit-transform: scaleY(1); transform: scaleY(1);} 4.3% {opacity: 1; -webkit-transform: scaleY(4); transform: scaleY(4);} 43% {opacity: 1; -webkit-transform: scaleX(10) rotate(60deg); transform: scaleX(10) rotate (60deg);} }
 .wrap { top: 30%; left: 25%; height: 200px; margin-top: -100px; position: absolute; } code { color: white; } span.blue { color: #48beef; } span.comment { color: #7f8c8d; } span.orange { color: #f39c12; } span.green { color: #33cc33; } .viewFull { font-family:OCR-A; color:orange; text-decoration:; } } @media only screen and (min-height: 500px) { .viewFull{ display:none; } } </style> <center> 
<style>
 img { filter:alpha(opacity=70); -moz-opacity:0.7; opacity:0.7; } 
img:hover { filter:alpha(opacity=100); -moz-opacity:.0; opacity:1.0; }
</style>
<body bgcolor="black">
<center><br/><br/><br/><br/>
<div class="error">
<img src="'.$gambar.'" align="center" width="250"></img></div>
</center><br/>
<center>
<div class="error"><red>[ </red><font>Hacked <red>By</red> '.$nick.'<red> ]</red>
<br><br><red>[</red> '.$pesan.' <red>]</red><br/><br/>
<red>[ </red><marquee behavior="alternate" width="80%" scrollamount="20" scrolldelay="0">'.nickteman.'</marquee><red> ]</red></font></center></div></body>');
$dw=fopen("$file.txt", "w");
fwrite($dw, '<!-- Generated By KannaiX007 -->
<html><head>
<title>'.$title.'</title>
<meta name="author" content="'.nick.'"/>
	<meta name="description" content="'.$deskripsi.'"/>
	<meta property="og:image" content="'.$gambar.'"/>
	<link rel="shortcut icon" href="'.$gambar.'"/>
</head>
<style>
	font{font-size:20px; color:white;}
	red{color:red;}
	.error { text-align: center; -webkit-animation: noise-3 1s linear infinite; animation: noise-3 1s linear infinite; overflow: default; }
 .info { text-align: center; width: 200px; height: 60px; margin: auto; position: absolute; top: 280px; bottom: 0; left: 20px; right: 0; -webkit-animation: noise-3 1s linear infinite; animation: noise-3 1s linear infinite; }
 .info:after { font-family: OCR-A; font-size: 100px; text-align: center; width: 800px; margin: auto; position: absolute; top: 20px; bottom: 0; left: 40px; right: 0; opacity: 0; color: white; -webkit-animation: noise-1 .2s linear infinite; animation: noise-1 .2s linear infinite; } @-webkit-keyframes noise-1 { 0%, 20%, 40%, 60%, 70%, 90% {opacity: 0;} 10% {opacity: .1;} 50% {opacity: .5; left: -6px;} 80% {opacity: .3;} 100% {opacity: .6; left: 2px;} } @keyframes noise-1 { 0%, 20%, 40%, 60%, 70%, 90% {opacity: 0;} 10% {opacity: .1;} 50% {opacity: .5; left: -6px;} 80% {opacity: .3;} 100% {opacity: .6; left: 2px;} } @-webkit-keyframes noise-2 { 0%, 20%, 40%, 60%, 70%, 90% {opacity: 0;} 10% {opacity: .1;} 50% {opacity: .5; left: 6px;} 80% {opacity: .3;} 100% {opacity: .6; left: -2px;} } @keyframes noise-2 { 0%, 20%, 40%, 60%, 70%, 90% {opacity: 0;} 10% {opacity: .1;} 50% {opacity: .5; left: 6px;} 80% {opacity: .3;} 100% {opacity: .6; left: -2px;} } @-webkit-keyframes noise { 0%, 3%, 5%, 42%, 44%, 100% {opacity: 1; -webkit-transform: scaleY(1); transform: scaleY(1);} 4.3% {opacity: 1; -webkit-transform: scaleY(1.7); transform: scaleY(1.7);} 43% {opacity: 1; -webkit-transform: scaleX(1.5); transform: scaleX(1.5);} } @keyframes noise { 0%, 3%, 5%, 42%, 44%, 100% {opacity: 1; -webkit-transform: scaleY(1); transform: scaleY(1);} 4.3% {opacity: 1; -webkit-transform: scaleY(1.7); transform: scaleY(1.7);} 43% {opacity: 1; -webkit-transform: scaleX(1.5); transform: scaleX(1.5);} } @-webkit-keyframes noise-3 { 0%,3%,5%,42%,44%,100% {opacity: 1; -webkit-transform: scaleY(1); transform: scaleY(1);} 4.3% {opacity: 1; -webkit-transform: scaleY(4); transform: scaleY(4);} 43% {opacity: 1; -webkit-transform: scaleX(10) rotate(60deg); transform: scaleX(10) rotate (60deg);} } @keyframes noise-3 { 0%,3%,5%,42%,44%,100% {opacity: 1; -webkit-transform: scaleY(1); transform: scaleY(1);} 4.3% {opacity: 1; -webkit-transform: scaleY(4); transform: scaleY(4);} 43% {opacity: 1; -webkit-transform: scaleX(10) rotate(60deg); transform: scaleX(10) rotate (60deg);} }
 .wrap { top: 30%; left: 25%; height: 200px; margin-top: -100px; position: absolute; } code { color: white; } span.blue { color: #48beef; } span.comment { color: #7f8c8d; } span.orange { color: #f39c12; } span.green { color: #33cc33; } .viewFull { font-family:OCR-A; color:orange; text-decoration:; } } @media only screen and (min-height: 500px) { .viewFull{ display:none; } } </style> <center> 
<style>
 img { filter:alpha(opacity=70); -moz-opacity:0.7; opacity:0.7; } 
img:hover { filter:alpha(opacity=100); -moz-opacity:.0; opacity:1.0; }
</style>
<body bgcolor="black">
<center><br/><br/><br/><br/>
<div class="error">
<img src="'.$gambar.'" align="center" width="250"></img></div>
</center><br/>
<center>
<div class="error"><red>[ </red><font>Hacked <red>By</red> '.$nick.'<red> ]</red>
<br><br><red>[</red> '.$pesan.' <red>]</red><br/><br/>
<red>[ </red><marquee behavior="alternate" width="80%" scrollamount="20" scrolldelay="0">'.nickteman.'</marquee><red> ]</red></font></center></div></body>');
	echo"<br><br><br><lime><h3>Lihat Script Deface Kamu -> <a href='$file.html'>$file.html</a>
<br>Ambil Script Deface Kamu -> <a href='$file.txt'>$file.txt</a>";
	}
	?>